# Generated by Django 5.2.6 on 2025-09-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=20)),
                ('validade_cnh', models.DateField()),
                ('categoria_cnh', models.CharField(max_length=5)),
                ('modelo_carro', models.CharField(max_length=50)),
                ('placa_carro', models.CharField(max_length=10)),
                ('cor_carro', models.CharField(max_length=20)),
                ('ano_carro', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
