# Generated by Django 5.2.6 on 2025-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='day',
            field=models.CharField(choices=[('mon', 'Segunda-feira'), ('tue', 'Terça-feira'), ('wed', 'Quarta-feira'), ('thu', 'Quinta-feira'), ('fri', 'Sexta-feira')], max_length=3),
        ),
    ]
