# Generated by Django 5.2.6 on 2025-11-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='University',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.university'),
        ),
    ]
