# Generated by Django 5.2.6 on 2025-11-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='University',
            new_name='university',
        ),
    ]
